# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none
pr: none

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/advance

pool:
  vmImage: macOs-latest

steps:

- script: |
    brew install terragrunt
    brew tap hashicorp/tap
    brew install hashicorp/tap/terraform
  displayName: 'Install Terragrunt and terraform'

- task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
  inputs:
    awsCredentials: 'Pawan_AdminAccess'
    regionName: 'ap-south-1'
    scriptType: inline
    inlineScript: |
        cd environments/dev/cluster_issuer
        terragrunt init -upgrade
        terragrunt destroy --auto-approve
  displayName: 'terragrunt cluster_issuer destroy'

- task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
  inputs:
    awsCredentials: 'Pawan_AdminAccess'
    regionName: 'ap-south-1'
    scriptType: inline
    inlineScript: |
        cd environments/dev/argocd
        terragrunt init -upgrade
        terragrunt destroy --auto-approve
  displayName: 'terragrunt argocd destroy'

- task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
  inputs:
    awsCredentials: 'Pawan_AdminAccess'
    regionName: 'ap-south-1'
    scriptType: inline
    inlineScript: |
        cd environments/dev/eks-addons
        terragrunt init -upgrade
        terragrunt destroy --auto-approve
  displayName: 'terragrunt eks-addons destroy'

- task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
  inputs:
    awsCredentials: 'Pawan_AdminAccess'
    regionName: 'ap-south-1'
    scriptType: inline
    inlineScript: |
        cd environments/dev/eks
        terragrunt init -upgrade
        terragrunt destroy --auto-approve
  displayName: 'terragrunt eks destroy'

- task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
  inputs:
    awsCredentials: 'Pawan_AdminAccess'
    regionName: 'ap-south-1'
    scriptType: inline
    inlineScript: >-
        cd environments/dev/vpc
        terragrunt init -upgrade
        terragrunt destroy --auto-approve
  displayName: 'terragrunt vpc destroy'
